#!/usr/bin/env python3
import sys
import unittest

paths = [arg for arg in sys.argv[1:] if not arg.startswith('-')]
verbose = '-v' in sys.argv
exit_code = 0
for path in paths or ['.']:
    suite = unittest.defaultTestLoader.discover(path)
    result = unittest.TextTestRunner(verbosity=2 if verbose else 1).run(suite)
    if not result.wasSuccessful():
        exit_code = 1
sys.exit(exit_code)
