global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'downloader_service'
    static_configs:
      - targets: ['downloader:8000']

  - job_name: 'embedding_generator'
    static_configs:
      - targets: ['embedding_generator:8001']

  - job_name: 'api_service'
    static_configs:
      - targets: ['api:8002']

  - job_name: 'redis_exporter'
    static_configs:
      - targets: ['redis_exporter:9121']

  - job_name: 'rabbitmq_exporter'
    static_configs:
      - targets: ['rabbitmq_exporter:9419']

  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['postgres_exporter:9187']
