{
 "title": "RabbitMQ Dashboard (Prometheus Exporter)",
 "description": "Tested with latest prometheus exporter, 2019-09",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "service",
    "query": "label_values(rabbitmq_channelsTotal, service)"
   },
   {
    "name": "pod",
    "label": "pod",
    "query": "label_values(rabbitmq_channelsTotal, pod)"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(rabbitmq_channelsTotal, namespace)"
   },
   {
    "name": "queue",
    "label": "queue",
    "query": "label_values(rabbitmq_queue_messages_get_total, queue)"
   },
   {
    "name": "vhost",
    "label": "vhost",
    "query": "label_values(rabbitmq_queue_messages_get_total, vhost)"
   }
  ]
 },
 "panels": [
  {
   "title": "$pod Messages",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_messages_ready_total{namespace=~\"$namespace\", pod=~\"$pod\", service=~\"$service\"}) / count(rabbitmq_queue_messages_ready_total{namespace=~\"$namespace\", pod=~\"$pod\", service=~\"$service\"})",
     "legendFormat": "$pod Messages"
    }
   ]
  },
  {
   "title": "$pod Consumers",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "targets": [
    {
     "expr": "sum(rabbitmq_consumersTotal{namespace=~\"$namespace\", pod=~\"$pod\", service=~\"$service\"}) / count(rabbitmq_consumersTotal{namespace=~\"$namespace\", pod=~\"$pod\", service=~\"$service\"})",
     "legendFormat": "$pod Consumers"
    }
   ]
  },
  {
   "title": "$pod Connections",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "sum(rabbitmq_connectionsTotal{namespace=~\"$namespace\", pod=~\"$pod\", service=~\"$service\"}) / count(rabbitmq_connectionsTotal{namespace=~\"$namespace\", pod=~\"$pod\", service=~\"$service\"})",
     "legendFormat": "$pod Connections"
    }
   ]
  },
  {
   "title": "$pod Channels",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 1, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum(rabbitmq_channelsTotal{namespace=~\"$namespace\", pod=~\"$pod\", service=~\"$service\"}) / count(rabbitmq_channelsTotal{namespace=~\"$namespace\", pod=~\"$pod\", service=~\"$service\"})",
     "legendFormat": "$pod Channels"
    }
   ]
  },
  {
   "title": "$pod Exchanges",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 1, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "sum(rabbitmq_exchangesTotal{namespace=~\"$namespace\", pod=~\"$pod\", service=~\"$service\"}) / count(rabbitmq_exchangesTotal{namespace=~\"$namespace\", pod=~\"$pod\", service=~\"$service\"})",
     "legendFormat": "$pod Exchanges"
    }
   ]
  },
  {
   "title": "$pod Partitions",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 1, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum by (queue) (rabbitmq_partitions{namespace=~\"$namespace\", pod=~\"$pod\", service=~\"$service\"}) / count(rabbitmq_partitions{namespace=~\"$namespace\", pod=~\"$pod\", service=~\"$service\"})",
     "legendFormat": "$pod Queues"
    }
   ]
  },
  {
   "title": "$pod Queues",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 1, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "sum by (queue) (rabbitmq_queuesTotal{namespace=~\"$namespace\", pod=~\"$pod\", service=~\"$service\"}) / count(rabbitmq_queuesTotal{namespace=~\"$namespace\", pod=~\"$pod\", service=~\"$service\"})",
     "legendFormat": "$pod Queues"
    }
   ]
  },
  {
   "title": "MSGS PUB by $pod",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rabbitmq_exchange_messages_published_in_total{namespace=~\"$namespace\", pod=~\"$pod\", service=~\"$service\"}) / count(rabbitmq_exchange_messages_published_in_total{namespace=~\"$namespace\", pod=~\"$pod\", service=~\"$service\"})",
     "legendFormat": "$pod Messages"
    }
   ]
  },
  {
   "title": "MSGS SUBS by $pod",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rabbitmq_exchange_messages_published_out_total{namespace=~\"$namespace\", pod=~\"$pod\", service=~\"$service\"}) / count(rabbitmq_exchange_messages_published_out_total{namespace=~\"$namespace\", pod=~\"$pod\", service=~\"$service\"})",
     "legendFormat": "$pod Messages"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rabbitmq_node_mem_used{namespace=~\"$namespace\", pod=~\"$pod\", service=~\"$service\"}) / count(rabbitmq_node_mem_used{namespace=~\"$namespace\", pod=~\"$pod\", service=~\"$service\"})",
     "legendFormat": "$pod Messages"
    }
   ]
  },
  {
   "title": "Disk Free",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rabbitmq_node_disk_free{namespace=~\"$namespace\", pod=~\"$pod\", service=~\"$service\"}) / count(rabbitmq_node_disk_free{namespace=~\"$namespace\", pod=~\"$pod\", service=~\"$service\"})",
     "legendFormat": "$pod Messages"
    }
   ]
  },
  {
   "title": "Used Memory by Messages",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_messages_ram{namespace=~\"$namespace\", pod=~\"$pod\", service=~\"$service\"}) / count(rabbitmq_queue_messages_ram{namespace=~\"$namespace\", pod=~\"$pod\", service=~\"$service\"})",
     "legendFormat": "$pod Messages"
    }
   ]
  },
  {
   "title": "Queue Size (Bytes)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_message_bytes{namespace=~\"$namespace\", pod=~\"$pod\", service=~\"$service\"}) / count(rabbitmq_queue_message_bytes{namespace=~\"$namespace\", pod=~\"$pod\", service=~\"$service\"})",
     "legendFormat": "$pod Messages"
    }
   ]
  },
  {
   "title": "Nodes UP",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 0 },
   "targets": [
    {
     "expr": "sum(count by (pod) (rabbitmq_queue_messages_ready_total))",
     "legendFormat": "$pod Messages"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short", "label": "messages" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (increase(rabbitmq_connectionsTotal[1m])) / ignoring (pod) group_left count(rabbitmq_connectionsTotal)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Total Messages",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "messages" }
   ],
   "targets": [
    {
     "expr": "sum by (queue, vhost, pod) (increase(rabbitmq_queue_messages[1m])) / ignoring (queue, vhost, pod) group_left count(rabbitmq_queue_messages)",
     "legendFormat": "[{{pod}}]-[{{queue}}]"
    }
   ]
  },
  {
   "title": "Messages Overview",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "messages" }
   ],
   "targets": [
    {
     "expr": "sum by (queue) (increase(rabbitmq_queue_messages_ready{service=~\"$service\", pod=~\"$pod\", namespace=~\"$namespace\", queue=~\"$queue\", vhost=~\"$vhost\"}[1m])) / ignoring (queue) group_left count(rabbitmq_queue_messages_ready{service=~\"$service\", pod=~\"$pod\", namespace=~\"$namespace\", queue=~\"$queue\", vhost=~\"$vhost\"})",
     "legendFormat": "[READY] {{queue}}"
    },
    {
     "expr": "sum by (queue) (increase(rabbitmq_queue_messages_published_total{service=~\"$service\", pod=~\"$pod\", namespace=~\"$namespace\", queue=~\"$queue\", vhost=~\"$vhost\"}[1m])) / ignoring (queue) group_left count(rabbitmq_queue_messages_published_total{service=~\"$service\", pod=~\"$pod\", namespace=~\"$namespace\", queue=~\"$queue\", vhost=~\"$vhost\"})",
     "legendFormat": "[PUBLISHED] {{queue}}"
    },
    {
     "expr": "sum by (queue) (increase(rabbitmq_queue_messages_delivered_total{service=~\"$service\", pod=~\"$pod\", namespace=~\"$namespace\", queue=~\"$queue\", vhost=~\"$vhost\"}[1m])) / ignoring (queue) group_left count(rabbitmq_queue_messages_delivered_total{service=~\"$service\", pod=~\"$pod\", namespace=~\"$namespace\", queue=~\"$queue\", vhost=~\"$vhost\"})",
     "legendFormat": "[DELIVERED] {{queue}}"
    },
    {
     "expr": "sum by (queue) (increase(rabbitmq_queue_messages_delivered_noack_total{service=~\"$service\", pod=~\"$pod\", namespace=~\"$namespace\", queue=~\"$queue\", vhost=~\"$vhost\"}[1m])) / ignoring (queue) group_left count(rabbitmq_queue_messages_delivered_noack_total{service=~\"$service\", pod=~\"$pod\", namespace=~\"$namespace\", queue=~\"$queue\", vhost=~\"$vhost\"})",
     "legendFormat": "[NOACK] {{queue}}"
    }
   ]
  },
  {
   "title": "ACK Messages",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short", "label": "messages" }
   ],
   "targets": [
    {
     "expr": "sum by (queue) (increase(rabbitmq_queue_messages_ack_total{queue=~\"$queue\", service=~\"$service\", pod=~\"$pod\", namespace=~\"$namespace\", vhost=~\"$vhost\"}[1m])) / ignoring (queue) group_left count(rabbitmq_queue_messages_ack_total{queue=~\"$queue\", service=~\"$service\", pod=~\"$pod\", namespace=~\"$namespace\", vhost=~\"$vhost\"})",
     "legendFormat": "{{ queue }}"
    }
   ]
  },
  {
   "title": "Delivered Messages",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short", "label": "messages" }
   ],
   "targets": [
    {
     "expr": "sum by (queue) (increase(rabbitmq_queue_messages_delivered_total{queue=~\"$queue\", service=~\"$service\", pod=~\"$pod\", namespace=~\"$namespace\", vhost=~\"$vhost\"}[1m])) / ignoring (queue) group_left count(rabbitmq_queue_messages_delivered_total{queue=~\"$queue\", service=~\"$service\", pod=~\"$pod\", namespace=~\"$namespace\", vhost=~\"$vhost\"})",
     "legendFormat": "{{ queue }}"
    }
   ]
  },
  {
   "title": "Returned Messages",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short", "label": "messages" }
   ],
   "targets": [
    {
     "expr": "sum by (queue) (increase(rabbitmq_queue_messages_returned_total{queue=~\"$queue\", service=~\"$service\", pod=~\"$pod\", namespace=~\"$namespace\", vhost=~\"$vhost\"}[1m])) / ignoring (queue) group_left count(rabbitmq_queue_messages_returned_total{queue=~\"$queue\", service=~\"$service\", pod=~\"$pod\", namespace=~\"$namespace\", vhost=~\"$vhost\"})",
     "legendFormat": "{{ queue }}"
    }
   ]
  }
 ]
}