name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
          pip install -r api_service/requirements.txt \
                      -r file_reader_service/requirements.txt \
                      -r downloader_service/requirements.txt \
                      -r embedding_service/src/tests/requirements-test.txt
      - name: Run tests
        run: bash run_all_tests.sh
